### PR TITLE
Added a table of content as bbcode element [toc] for webpages

### PR DESCRIPTION
**Pull request by einervonvielen**
- Included jquery.toc.js (http://www.apache.org/licenses/LICENSE-2.0)
- Modified jquery.toc.js to work with the webpages of the red#matrix
- Added info to the help

### CODE REVIEW

**Comment by friendica** [comment]
Apache has this clause B:
You must cause any modified files to carry prominent notices stating that You changed the files; and

So we're OK "at this time", but if anybody edits jquery.toc.js we could fall into a licensing issue if they don't document prominently in the file that changes were made. Noting this for now, but we need to keep on the lookout for edits to this file. We meaning everybody.

**Comment by friendica** [comment]
Ah I noticed it was edited and this was prominently noted. Never mind.... thank you.

**Comment by einervonvielen** [comment]
You're welcome!

**Comment by pafcu** [comment]
Would it make sense to try to get the changes merged upstream?

**Comment by einervonvielen** [comment]
It was.
Example here in my test page
https://friendicared.de/page/tom4694/manual_dev_red

**Pull request merged**
