### PR TITLE
Fixed bbode element toc for webpages

### PR DESCRIPTION
**Pull request by einervonvielen**
Cause: If the textarea "Title" is left empty in the webpage creator (https://hostname/webpages/username)
Response: Webpages can contain empty headings h3

### CODE REVIEW

**Comment by einervonvielen** [comment]
An alternative solution to this fix would be:
- leave the JS (that creates the table of content) as it is (unfixed)
AND
-  either a) Remove the "Title (optional)" from the webpage creator 
-  or b) Do not mark the Title of the webpage as h3-heading. Use big fonts instead.

**Comment by einervonvielen** [comment]
Thanks, friendica and pafu.

**Comment by pafcu** [comment]
@einervonvielen I meant https://github.com/ndabas/toc where the source is originally taken from. Someone else outside this project might have the same problems with the library.

**Comment by einervonvielen** [comment]
No. Why?
the JS-script takes parameters. One of them is the html element where it should find headers. This defaults to <body>.
I have thought about it:
- I will change the last "fix" back to the original version
- I will give the element as optional parameter, e.g. [toc=mydiv.myclass]. This value defaults to "body" if omitted.

**Comment by pafcu** [comment]
I'm not sure I understand what you mean. Also, you have to put HTML inside special blocks, or GitHub won't show it correctly. Check the "Markdown supported" link above the editor.

**Pull request merged**
