### PR TITLE
Fixed #846 Viewing event from calendar displays event

### LINKED ISSUE #846: Viewing event from calendar displays event info beneath colored bar representing event
In the calendar, when an event is viewed, by clicking the colored bar in the calendar representing the event, the info is displayed beneath the bar. This can be fixed in CSS by adding a largish z-index for #colorbox.

### PR DESCRIPTION
**Pull request by einervonvielen**
See https://github.com/friendica/red/issues/846

### CODE REVIEW

**Comment by einervonvielen** [comment]
Befor fix

bildschirmfoto vom 2015-01-18 01 58 48

**Comment by einervonvielen** [comment]
After fix

bildschirmfoto vom 2015-01-18 01 57 49

**Comment by pafcu** [comment]
Awesome! Thanks.

**Comment by einervonvielen** [comment]
Hey, Pacfu, YOU are the one who solved it. I just followed your explanations....

**Comment by pafcu** [comment]
@einervonvielen You underestimate the time it also takes to test solutions. Sometimes it's easy to look at the code and say what should be done. Doesn't mean it actually always works out like that :-) Also, it seems like you stumbled on another bug (the one with the hex colors), which I would not have noticed. This shows why it's so important for many people to work on the code. So, even if you don't want to take credit for fixing the bug, take credit for testing the fix.

**Pull request merged**
